# Reference: https://github.com/SeleniumHQ/docker-selenium
# Refer readme.md file section 'Step3: Test Execution' to see different ways of setting up grid and running tests (using docker-compose and swarm)

version: '3.7'
services:
  test-chrome:
    image: maven:3-jdk-8
    working_dir: '/test'
    volumes:
      - "./:/test"
    deploy:
      replicas: 1
    depends_on:
      - hub
      - chrome      
    command: sh -c "mvn clean test -Dhost=grid -Dbrowser=chrome -Dmaven.test.failure.ignore=true
        && tail -f /dev/null"