# Reference: https://github.com/SeleniumHQ/docker-selenium
# To start Docker in Swarm mode, you need to run `docker swarm init`
# To deploy the Grid, `docker stack deploy -c docker-compose.yml grid`
# Check if grid is active or not: http://localhost:4444/grid/console 
# list services with `docker service ls` 
# Scale any service as `docker service scale grid_chrome=5` or/and `docker service scale grid_firefox=3`
# Check if grid scaled: http://localhost:4444/grid/console 
# list stack with `docker stack ls`
# Now to run tests
  # First go to the Driver class and uncomment the driver you want to select for running (from line 56 - grid)
  # say you want: ChromeOptions options = new ChromeOptions(); [uncomment this and comment other driver types in this if block (grid)]
  # Now you can go to your command line (local/CI) and run tests on grid using: 
  # PS D:\WebdriverCI> `mvn clean test -Dbrowser=grid`
# Stop stack with `docker stack rm grid`
# Note: If you get errors in containes and you are not able to do another mvn clean test, 
  # then stop stack (with `docker stack rm grid`), 
  # and deploy the Grid again, `docker stack deploy -c docker-compose.yml grid`

version: '3.7'

services:
  hub:
   image: selenium/hub:3.141.59-20200525
   ports:
     - "4444:4444"

  chrome:
    image: selenium/node-chrome:3.141.59-20200525
    volumes:
      - /dev/shm:/dev/shm
    environment:
      HUB_HOST: hub
      HUB_PORT: 4444
    deploy:
        replicas: 1
    entrypoint: bash -c 'SE_OPTS="-host $$HOSTNAME" /opt/bin/entry_point.sh'

  firefox:
    image: selenium/node-firefox:3.141.59-20200525
    volumes:
      - /dev/shm:/dev/shm
    environment:
      HUB_HOST: hub
      HUB_PORT: 4444
    deploy:
        replicas: 1
    entrypoint: bash -c 'SE_OPTS="-host $$HOSTNAME" /opt/bin/entry_point.sh'

  opera:
    image: selenium/node-opera:3.141.59-20200525
    volumes:
      - /dev/shm:/dev/shm
    environment:
      HUB_HOST: hub
      HUB_PORT: 4444
    deploy:
        replicas: 1
    entrypoint: bash -c 'SE_OPTS="-host $$HOSTNAME" /opt/bin/entry_point.sh'