# Reference: https://github.com/SeleniumHQ/docker-selenium
# Option A: To run grid and tests via docker-compose (run): 
  # `docker-compose -f .\docker-compose-grid.yml -f .\docker-compose-test.yml up`
# Ctrl+c to exit.
# Before restart:
  # `docker container stop $(docker container ls -aq)`
  # `docker container rm $(docker container ls -aq)`  
# You can restart again:
  # `docker-compose -f .\docker-compose-grid.yml -f .\docker-compose-test.yml up`
# Option B: To keep this comments in check, instructions to run grid and tests via docker swarm is explained in the file docker-compose-grid.yml
# file comments.  

version: '3.7'
services:
  test-chrome:
    image: maven:3-jdk-8
    working_dir: '/test'
    volumes:
      - "./:/test"
    deploy:
      replicas: 1
    depends_on:
      - hub
      - chrome      
    command: sh -c "mvn clean test -Dhost=grid -Dbrowser=chrome -Dmaven.test.failure.ignore=true
        && tail -f /dev/null"