# Reference: https://github.com/SeleniumHQ/docker-selenium
# Refer readme.md file section 'Step3: Test Execution' to see different ways of setting up grid and running tests (using docker-compose and swarm)

# If you want to give a default test and then keep container alive (not needed anymore with our new approach to do this)
# command: sh -c "mvn clean test -Dhost=grid -DaccessGridFrom=container -Dbrowser=chrome -Dmaven.test.failure.ignore=true
#     && tail -f /dev/null"

# I am keeping the container name as container_name: grid_test. This is to keep the execution commands consistent
# in both docker-compose mode and in docker swarm mode

version: '3.7'
services:
  test:
    build: .
    image: test:mvn-3-jdk-8
    container_name: grid_test
    working_dir: '/usr/src'
    volumes:
      - "./:/usr/src"
      - /dev/shm:/dev/shm
    deploy:
      replicas: 1  
    command: sh -c "echo 'ready to test' && tail -f /dev/null"