# An override file to use when you want to run tests on grid containers, from test containers. 
# This will make sure that the test container will wait for grid containers to be up, before starting test container.

version: '3.7'
services:
  test:
    depends_on:
      - hub
      - chrome      